### all limited

GET http://localhost:8080/all/7

<> 2023-07-29T095157.200.json

### use @Query
GET http://localhost:8080/color



### use limit and SpEL
GET http://localhost:8080/color_limited/velvet/2



###